### PR TITLE
6552 Create splash screen

### PR DESCRIPTION
**Pull request by Hiepsisoma**
https://edu-redmine.framgia.vn/issues/6552

### CODE REVIEW

**Comment by Hiepsisoma** [comment]
ready

**Comment by Hiepsisoma** [comment]
ready

**Review by DoanVanToan — CHANGES_REQUESTED** [review]
Update redmine

**Comment by Hiepsisoma** [comment]
ready

**Review by NguyenMinhTuanB — APPROVED** [review]

**Pull request merged**
